application: fisherds-ae-movie-quotes
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/spi/.*
  script: api.py

#- url: (.*)/
#  static_files: static\1/moviequotes.html
#  upload: static
#  secure: always

# Serving static files (js, css, images, etc)
- url: /static
  static_dir: static

libraries:
- name: endpoints
  version: 1.0
